name: CI

on: [push]

jobs:
  mac:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v1
    - name: Dependencies
      run: |
        brew install protobuf go cmake
    - name: Build
      run: cargo build --verbose
    - name: Run tests 
      run: cargo test --verbose
  windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v1
    - name: Dependencies
      run: |
        Set-ExecutionPolicy RemoteSigned -scope CurrentUser
        Invoke-Expression (New-Object System.Net.WebClient).DownloadString('https://get.scoop.sh')
        scoop bucket add extras
        scoop install protobuf go cmake
    - name: Build
      run: cargo build --all --verbose
    - name: Run tests
      run: cargo test --all --verbose -- --nocapture
  ubuntu:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Dependencies
      run: |
        sudo apt install --yes protobuf cmake go
    - name: Build
      run: cargo build --verbose
    - name: Run tests 
      run: cargo test --verbose --all --features integration-tests -- --nocapture
      env:
        PD_ADDR: "127.0.0.1:2379"
    services:
      pd:
        image: pingcap/pd
        ports:
          - 2379:2379
          - 2380:2380
        options: "--network-alias pd.test"
      tikv:
        image: pingcap/tikv
        ports:
          - 20160:20160
        options: "--network-alias tikv.test"

