name: CI

on: [push]

jobs:
  mac:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v1
    - name: Dependencies
      shell: bash
      run: |
        brew install protobuf go cmake rustup
        rustup-init --default-toolchain `cat rust-toolchain` -y
        source ~/.cargo/env
    - name: Build
      shell: bash
      run: |
        source ~/.cargo/env
        cargo build
    - name: Run tests
      shell: bash
      run: |
        source ~/.cargo/env
        cargo test --all -- --nocapture

  windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v1
    - name: Dependencies
      shell: powershell
      run: |
        Set-ExecutionPolicy RemoteSigned -scope CurrentUser
        Invoke-Expression (New-Object System.Net.WebClient).DownloadString('https://get.scoop.sh')
        scoop bucket add extras
        scoop install protobuf go cmake rustup
        rustup default set $(Get-Content -Path ./rust-toolchain)
    - name: Build
      shell: powershell
      run: |
        cargo build --all
    - name: Run tests
      shell: powershell
      run: |
        cargo test --all -- --nocapture

  ubuntu:
    runs-on: ubuntu-latest
    services:
      pd:
        image: pingcap/pd
        ports:
          - 2379:2379
          - 2380:2380
      tikv:
        image: pingcap/tikv
        ports:
          - 20160:20160
    steps:
    - uses: actions/checkout@v1
    - name: Dependencies
      shell: bash
      run: |
        sudo apt install --yes protobuf cmake go
        rustup default set `cat rust-toolchain`
    - name: Format
      shell: bash
      run: |
        rustup component add rustfmt
        cargo fmt -- --check
    - name: Clippy
      shell: bash
      run: |
        rustup component add clippy
        cargo clippy -- -D clippy::all
    - name: Build
      shell: bash
      run: |
        cargo build
    - name: Run tests 
      shell: bash
      run: |
        cargo test --all --features integration-tests -- --nocapture

