name: Test

on: [push]

jobs:
  Mac:
    runs-on: macOS-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Dependencies
      shell: bash
      run: |
        brew install protobuf go cmake
    - name: Install Rust toolchain
      uses: actions-rs/toolchain@v1
      with:
          toolchain: beta
    - name: Test
      uses: actions-rs/cargo@v1
      with:
        command: test
        args: -- --nocapture

  Windows:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Install dependencies
      shell: powershell
      run: |
        Set-ExecutionPolicy RemoteSigned -scope CurrentUser
        Invoke-Expression (New-Object System.Net.WebClient).DownloadString('https://get.scoop.sh')
        scoop bucket add extras
        scoop install protobuf go cmake llvm
    - name: Install Rust toolchain
      uses: actions-rs/toolchain@v1
      with:
          toolchain: beta
    - name: Test
      uses: actions-rs/cargo@v1
      with:
        command: test
        args: -- --nocapture

  Ubuntu:
    runs-on: ubuntu-latest
    services:
      pd:
        image: pingcap/pd
        ports:
          - 2379:2379
          - 2380:2380
      tikv:
        image: pingcap/tikv
        ports:
          - 20160:20160
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Install dependencies
      shell: bash
      run: |
        sudo apt update
        sudo apt install --yes protobuf-compiler cmake golang llvm libgflags-dev libprotobuf-dev pkg-config
    - name: Install Rust toolchain
      uses: actions-rs/toolchain@v1
      with:
          toolchain: beta
    - name: Test
      uses: actions-rs/cargo@v1
      with:
        command: test
        args: --features integration-tests -- --nocapture

