name: Test

on: [push]

jobs:
  Mac:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v1
    - name: Dependencies
      shell: bash
      run: |
        brew install protobuf go cmake
    - uses: actions-rs/toolchain@v1
      with:
          toolchain: nightly
    - uses: actions-rs/cargo@v1
      with:
        command: test
        args: -- --nocapture

  Windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v1
    - name: Dependencies
      shell: powershell
      run: |
        Set-ExecutionPolicy RemoteSigned -scope CurrentUser
        Invoke-Expression (New-Object System.Net.WebClient).DownloadString('https://get.scoop.sh')
        scoop bucket add extras
        scoop install protobuf go cmake
    - uses: actions-rs/toolchain@v1
      with:
          toolchain: nightly
    - uses: actions-rs/cargo@v1
      with:
        command: test
        args: -- --nocapture

  Ubuntu:
    runs-on: ubuntu-latest
    services:
      pd:
        image: pingcap/pd
        ports:
          - 2379:2379
          - 2380:2380
      tikv:
        image: pingcap/tikv
        ports:
          - 20160:20160
    steps:
    - uses: actions/checkout@v1
    - name: Dependencies
      shell: bash
      run: |
        sudo apt update
        sudo apt install --yes protobuf cmake go
    - uses: actions-rs/toolchain@v1
      with:
          toolchain: nightly
    - uses: actions-rs/cargo@v1
      with:
        command: test
        args: --features integration-tests -- --nocapture

